"""Add AI, Resource, Community, Ledger, Notification tables for Sprint B

Revision ID: 43adde7206df
Revises: 
Create Date: 2026-04-04 21:53:27.336094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43adde7206df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('before_data', sa.Text(), nullable=True),
    sa.Column('after_data', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('prev_log_hash', sa.String(length=64), nullable=False),
    sa.Column('log_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_hash')
    )
    op.create_index(op.f('ix_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_admin_id'), 'admin_audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_created_at'), 'admin_audit_logs', ['created_at'], unique=False)
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('allowed_subnet', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('ai_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('has_attachment', sa.Boolean(), nullable=False),
    sa.Column('attachment_ids', sa.String(length=500), nullable=True),
    sa.Column('feedback_type', sa.String(length=20), nullable=True),
    sa.Column('feedback_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_created', 'ai_messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_messages_session_id'), 'ai_messages', ['session_id'], unique=False)
    op.create_table('ai_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('system_prompt_version', sa.String(length=50), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_created', 'ai_sessions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_sessions_user_id'), 'ai_sessions', ['user_id'], unique=False)
    op.create_table('asset_packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price_beans', sa.Integer(), nullable=False),
    sa.Column('quota_mb', sa.Integer(), nullable=False),
    sa.Column('discount_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempted_transaction',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('order_type', sa.Enum('DOWNLOAD', 'DOWNLOAD_REVENUE', 'DESTRUCTION', 'RECHARGE', 'SYSTEM_GIFT', 'SHARE_REWARD', 'EARLYBIRD_REWARD', 'SIGN_IN', 'INVITE_REWARD', 'CONTENT_TOPIC', 'CONTENT_POST', 'CATEGORY_FIRST_POST_REWARD', 'CONTENT_ADOPTED', 'BOUNTY_LOCK', 'BOUNTY_RELEASE', 'BOUNTY_REFUND', 'FEEDBACK_AWARD', name='ordertype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempted_transaction_user_id'), 'attempted_transaction', ['user_id'], unique=False)
    op.create_table('file_meta',
    sa.Column('file_uuid', sa.String(length=36), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('oss_path', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('ref_counts', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=50), nullable=False),
    sa.Column('uploader_uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('file_uuid')
    )
    op.create_index(op.f('ix_file_meta_file_hash'), 'file_meta', ['file_hash'], unique=True)
    op.create_index(op.f('ix_file_meta_lifecycle_status'), 'file_meta', ['lifecycle_status'], unique=False)
    op.create_index(op.f('ix_file_meta_status'), 'file_meta', ['status'], unique=False)
    op.create_index(op.f('ix_file_meta_uploader_uid'), 'file_meta', ['uploader_uid'], unique=False)
    op.create_table('file_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_uuid', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_usage_file_uuid'), 'file_usage', ['file_uuid'], unique=False)
    op.create_index(op.f('ix_file_usage_target_id'), 'file_usage', ['target_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('receiver_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('SYSTEM', 'INTERACTION', 'AUDIT', 'REWARD', 'BROADCAST', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('NORMAL', 'HIGH', name='notificationpriority'), nullable=False),
    sa.Column('is_broadcast_exemption', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_receiver_id'), 'notifications', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_table('point_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('point_type', sa.Enum('GOLD_BEAN', 'BONUS_BEAN', name='pointtype'), nullable=False),
    sa.Column('dist_ratio', sa.Float(), nullable=True),
    sa.Column('order_type', sa.Enum('DOWNLOAD', 'DOWNLOAD_REVENUE', 'DESTRUCTION', 'RECHARGE', 'SYSTEM_GIFT', 'SHARE_REWARD', 'EARLYBIRD_REWARD', 'SIGN_IN', 'INVITE_REWARD', 'CONTENT_TOPIC', 'CONTENT_POST', 'CATEGORY_FIRST_POST_REWARD', 'CONTENT_ADOPTED', 'BOUNTY_LOCK', 'BOUNTY_RELEASE', 'BOUNTY_REFUND', 'FEEDBACK_AWARD', name='ordertype'), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('related_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_ledger_created_at'), 'point_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_point_ledger_order_type'), 'point_ledger', ['order_type'], unique=False)
    op.create_index(op.f('ix_point_ledger_related_id'), 'point_ledger', ['related_id'], unique=False)
    op.create_index(op.f('ix_point_ledger_transaction_uuid'), 'point_ledger', ['transaction_uuid'], unique=False)
    op.create_index(op.f('ix_point_ledger_user_id'), 'point_ledger', ['user_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('anonymized_user_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_anonymized_user_hash'), 'posts', ['anonymized_user_hash'], unique=False)
    op.create_index(op.f('ix_posts_topic_id'), 'posts', ['topic_id'], unique=False)
    op.create_table('resource_previews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('preview_url', sa.String(length=1024), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_previews_resource_id'), 'resource_previews', ['resource_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('uploader_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('file_uuid', sa.String(length=36), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('dislike_count', sa.Integer(), nullable=False),
    sa.Column('heat_score', sa.Float(), nullable=False),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('SCANNING', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'APPEALING', 'BLOCKED', name='resourcestatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('anonymized_user_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_anonymized_user_hash'), 'resources', ['anonymized_user_hash'], unique=False)
    op.create_index(op.f('ix_resources_created_at'), 'resources', ['created_at'], unique=False)
    op.create_index(op.f('ix_resources_heat_score'), 'resources', ['heat_score'], unique=False)
    op.create_index(op.f('ix_resources_title'), 'resources', ['title'], unique=False)
    op.create_index(op.f('ix_resources_uploader_id'), 'resources', ['uploader_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('bounty_amount', sa.Integer(), nullable=False),
    sa.Column('bounty_status', sa.Enum('NONE', 'ACTIVE', 'RESOLVED', 'REFUNDED', name='bountystatus'), nullable=False),
    sa.Column('accepted_post_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('NORMAL', 'BLOCKED', 'PENDING', name='topicstatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('heat_score', sa.Float(), nullable=False),
    sa.Column('anonymized_user_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_anonymized_user_hash'), 'topics', ['anonymized_user_hash'], unique=False)
    op.create_index(op.f('ix_topics_author_id'), 'topics', ['author_id'], unique=False)
    op.create_index(op.f('ix_topics_created_at'), 'topics', ['created_at'], unique=False)
    op.create_index(op.f('ix_topics_heat_score'), 'topics', ['heat_score'], unique=False)
    op.create_table('user_purchased_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('remaining_mb', sa.Integer(), nullable=False),
    sa.Column('used_mb', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_purchased_assets_user_id'), 'user_purchased_assets', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wechat_openid', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=512), nullable=True),
    sa.Column('phone_blind_index', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('rank', sa.String(length=20), nullable=False),
    sa.Column('reputation_points', sa.Integer(), nullable=False),
    sa.Column('reputation_status', sa.String(length=20), nullable=False),
    sa.Column('is_expert', sa.Boolean(), nullable=False),
    sa.Column('gold_beans', sa.Integer(), nullable=False),
    sa.Column('bonus_beans', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=20), nullable=True),
    sa.Column('referrer_id', sa.String(length=36), nullable=True),
    sa.Column('is_reward_triggered', sa.Boolean(), nullable=False),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('last_login_device', sa.String(length=255), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('lock_until_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agreement_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_subnet', sa.Text(), nullable=True),
    sa.Column('daily_token_usage', sa.Integer(), nullable=False),
    sa.Column('total_ai_storage_mb', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_invite_code'), 'users', ['invite_code'], unique=True)
    op.create_index(op.f('ix_users_phone_blind_index'), 'users', ['phone_blind_index'], unique=True)
    op.create_index(op.f('ix_users_referrer_id'), 'users', ['referrer_id'], unique=False)
    op.create_index(op.f('ix_users_wechat_openid'), 'users', ['wechat_openid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_wechat_openid'), table_name='users')
    op.drop_index(op.f('ix_users_referrer_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone_blind_index'), table_name='users')
    op.drop_index(op.f('ix_users_invite_code'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_purchased_assets_user_id'), table_name='user_purchased_assets')
    op.drop_table('user_purchased_assets')
    op.drop_index(op.f('ix_topics_heat_score'), table_name='topics')
    op.drop_index(op.f('ix_topics_created_at'), table_name='topics')
    op.drop_index(op.f('ix_topics_author_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_anonymized_user_hash'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_resources_uploader_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_title'), table_name='resources')
    op.drop_index(op.f('ix_resources_heat_score'), table_name='resources')
    op.drop_index(op.f('ix_resources_created_at'), table_name='resources')
    op.drop_index(op.f('ix_resources_anonymized_user_hash'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_resource_previews_resource_id'), table_name='resource_previews')
    op.drop_table('resource_previews')
    op.drop_index(op.f('ix_posts_topic_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_anonymized_user_hash'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_point_ledger_user_id'), table_name='point_ledger')
    op.drop_index(op.f('ix_point_ledger_transaction_uuid'), table_name='point_ledger')
    op.drop_index(op.f('ix_point_ledger_related_id'), table_name='point_ledger')
    op.drop_index(op.f('ix_point_ledger_order_type'), table_name='point_ledger')
    op.drop_index(op.f('ix_point_ledger_created_at'), table_name='point_ledger')
    op.drop_table('point_ledger')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_receiver_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_file_usage_target_id'), table_name='file_usage')
    op.drop_index(op.f('ix_file_usage_file_uuid'), table_name='file_usage')
    op.drop_table('file_usage')
    op.drop_index(op.f('ix_file_meta_uploader_uid'), table_name='file_meta')
    op.drop_index(op.f('ix_file_meta_status'), table_name='file_meta')
    op.drop_index(op.f('ix_file_meta_lifecycle_status'), table_name='file_meta')
    op.drop_index(op.f('ix_file_meta_file_hash'), table_name='file_meta')
    op.drop_table('file_meta')
    op.drop_index(op.f('ix_attempted_transaction_user_id'), table_name='attempted_transaction')
    op.drop_table('attempted_transaction')
    op.drop_table('asset_packages')
    op.drop_index(op.f('ix_ai_sessions_user_id'), table_name='ai_sessions')
    op.drop_index('idx_user_created', table_name='ai_sessions')
    op.drop_table('ai_sessions')
    op.drop_index(op.f('ix_ai_messages_session_id'), table_name='ai_messages')
    op.drop_index('idx_session_created', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index(op.f('ix_admin_audit_logs_created_at'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_admin_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_action'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    # ### end Alembic commands ###
