"""add_system_configs_table

Revision ID: db349918942c
Revises: 0e68152e456f
Create Date: 2026-04-19 20:33:04.116789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db349918942c'
down_revision: Union[str, None] = '0e68152e456f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensitive_word_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('matched_words', sa.String(length=1000), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('additional_data', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sensitive_word_logs_created', 'sensitive_word_logs', ['created_at'], unique=False)
    op.create_index('idx_sensitive_word_logs_user_action', 'sensitive_word_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('ix_sensitive_word_logs_content_hash'), 'sensitive_word_logs', ['content_hash'], unique=False)
    op.create_index(op.f('ix_sensitive_word_logs_session_id'), 'sensitive_word_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_sensitive_word_logs_user_id'), 'sensitive_word_logs', ['user_id'], unique=False)
    op.create_table('sensitive_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('POLITICAL', 'VIOLENCE', 'PORNOGRAPHY', 'GAMBLING', 'DRUGS', 'FRAUD', 'RUMOR', 'INSULT', 'ADVERTISEMENT', 'OTHER', name='sensitive_word_category'), nullable=False),
    sa.Column('level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='sensitive_word_level'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sensitive_words_category', 'sensitive_words', ['category'], unique=False)
    op.create_index('idx_sensitive_words_enabled_hit', 'sensitive_words', ['enabled', 'hit_count'], unique=False)
    op.create_index('idx_sensitive_words_level', 'sensitive_words', ['level'], unique=False)
    op.create_index(op.f('ix_sensitive_words_enabled'), 'sensitive_words', ['enabled'], unique=False)
    op.create_index(op.f('ix_sensitive_words_word'), 'sensitive_words', ['word'], unique=True)
    op.create_table('system_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_config_key'), 'system_configs', ['config_key'], unique=True)
    op.create_table('search_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('search_type', sa.String(length=20), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_history_keyword', 'search_history', ['keyword'], unique=False)
    op.create_index('idx_search_history_user_created', 'search_history', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_search_history_id'), 'search_history', ['id'], unique=False)
    op.create_index(op.f('ix_search_history_keyword'), 'search_history', ['keyword'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.alter_column('ai_messages', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_foreign_key(None, 'ai_messages', 'ai_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ai_sessions', 'total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index('idx_ai_sessions_title', table_name='ai_sessions', postgresql_using='gin')
    op.drop_index('idx_ai_sessions_user_created', table_name='ai_sessions')
    op.drop_constraint('fk_ai_sessions_provider', 'ai_sessions', type_='foreignkey')
    op.add_column('balance_transactions', sa.Column('additional_data', sa.String(length=2000), nullable=True))
    op.drop_index('idx_balance_transactions_order_id', table_name='balance_transactions')
    op.drop_index('idx_balance_transactions_user_id', table_name='balance_transactions')
    op.create_index(op.f('ix_balance_transactions_payment_order_id'), 'balance_transactions', ['payment_order_id'], unique=False)
    op.create_index(op.f('ix_balance_transactions_user_id'), 'balance_transactions', ['user_id'], unique=False)
    op.drop_column('balance_transactions', 'metadata')
    op.create_foreign_key(None, 'file_usage', 'file_meta', ['file_uuid'], ['file_uuid'], ondelete='CASCADE')
    op.alter_column('llm_providers', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('llm_providers', 'rate_limit_per_minute',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('payment_orders', sa.Column('additional_data', sa.String(length=2000), nullable=True))
    op.alter_column('payment_orders', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('payment_orders', 'payment_method',
               existing_type=postgresql.ENUM('wechat', 'alipay', 'bank_transfer', name='paymentmethod'),
               nullable=False)
    op.alter_column('payment_orders', 'payment_status',
               existing_type=postgresql.ENUM('pending', 'success', 'failed', 'refunded', 'cancelled', name='paymentstatus'),
               nullable=False)
    op.drop_index('idx_payment_orders_order_no', table_name='payment_orders')
    op.drop_index('idx_payment_orders_user_id', table_name='payment_orders')
    op.create_index(op.f('ix_payment_orders_order_no'), 'payment_orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_payment_orders_user_id'), 'payment_orders', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'payment_orders', ['transaction_id'])
    op.drop_column('payment_orders', 'metadata')
    op.create_foreign_key(None, 'posts', 'posts', ['parent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'posts', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_resources_category_status_created', table_name='resources')
    op.drop_index('idx_resources_description', table_name='resources', postgresql_using='gin')
    op.drop_index('idx_resources_fts', table_name='resources', postgresql_using='gin')
    op.drop_index('idx_resources_tags', table_name='resources', postgresql_using='gin')
    op.drop_index('idx_resources_title', table_name='resources')
    op.drop_index('idx_topics_category_heat', table_name='topics')
    op.drop_index('idx_topics_content', table_name='topics', postgresql_using='gin')
    op.drop_index('idx_topics_fts', table_name='topics', postgresql_using='gin')
    op.drop_index('idx_topics_title', table_name='topics')
    op.drop_index('idx_user_balances_user_id', table_name='user_balances')
    op.create_index(op.f('ix_user_balances_user_id'), 'user_balances', ['user_id'], unique=True)
    op.drop_index('idx_users_nickname', table_name='users', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_nickname', 'users', ['nickname'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_user_balances_user_id'), table_name='user_balances')
    op.create_index('idx_user_balances_user_id', 'user_balances', ['user_id'], unique=True)
    op.create_index('idx_topics_title', 'topics', ['title'], unique=False)
    op.create_index('idx_topics_fts', 'topics', [sa.text("to_tsvector('simple'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(content, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index('idx_topics_content', 'topics', ['content'], unique=False, postgresql_using='gin')
    op.create_index('idx_topics_category_heat', 'topics', ['category_id', 'heat_score'], unique=False)
    op.create_index('idx_resources_title', 'resources', ['title'], unique=False)
    op.create_index('idx_resources_tags', 'resources', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_resources_fts', 'resources', [sa.text("to_tsvector('simple'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index('idx_resources_description', 'resources', ['description'], unique=False, postgresql_using='gin')
    op.create_index('idx_resources_category_status_created', 'resources', ['category_id', 'status', 'created_at'], unique=False)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.add_column('payment_orders', sa.Column('metadata', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payment_orders', type_='unique')
    op.drop_index(op.f('ix_payment_orders_user_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_order_no'), table_name='payment_orders')
    op.create_index('idx_payment_orders_user_id', 'payment_orders', ['user_id'], unique=False)
    op.create_index('idx_payment_orders_order_no', 'payment_orders', ['order_no'], unique=True)
    op.alter_column('payment_orders', 'payment_status',
               existing_type=postgresql.ENUM('pending', 'success', 'failed', 'refunded', 'cancelled', name='paymentstatus'),
               nullable=True)
    op.alter_column('payment_orders', 'payment_method',
               existing_type=postgresql.ENUM('wechat', 'alipay', 'bank_transfer', name='paymentmethod'),
               nullable=True)
    op.alter_column('payment_orders', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.drop_column('payment_orders', 'additional_data')
    op.alter_column('llm_providers', 'rate_limit_per_minute',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('llm_providers', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'file_usage', type_='foreignkey')
    op.add_column('balance_transactions', sa.Column('metadata', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_balance_transactions_user_id'), table_name='balance_transactions')
    op.drop_index(op.f('ix_balance_transactions_payment_order_id'), table_name='balance_transactions')
    op.create_index('idx_balance_transactions_user_id', 'balance_transactions', ['user_id'], unique=False)
    op.create_index('idx_balance_transactions_order_id', 'balance_transactions', ['payment_order_id'], unique=False)
    op.drop_column('balance_transactions', 'additional_data')
    op.create_foreign_key('fk_ai_sessions_provider', 'ai_sessions', 'llm_providers', ['provider_id'], ['id'])
    op.create_index('idx_ai_sessions_user_created', 'ai_sessions', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_ai_sessions_title', 'ai_sessions', ['title'], unique=False, postgresql_using='gin')
    op.alter_column('ai_sessions', 'total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(None, 'ai_messages', type_='foreignkey')
    op.alter_column('ai_messages', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_keyword'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_id'), table_name='search_history')
    op.drop_index('idx_search_history_user_created', table_name='search_history')
    op.drop_index('idx_search_history_keyword', table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_system_configs_config_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_sensitive_words_word'), table_name='sensitive_words')
    op.drop_index(op.f('ix_sensitive_words_enabled'), table_name='sensitive_words')
    op.drop_index('idx_sensitive_words_level', table_name='sensitive_words')
    op.drop_index('idx_sensitive_words_enabled_hit', table_name='sensitive_words')
    op.drop_index('idx_sensitive_words_category', table_name='sensitive_words')
    op.drop_table('sensitive_words')
    op.drop_index(op.f('ix_sensitive_word_logs_user_id'), table_name='sensitive_word_logs')
    op.drop_index(op.f('ix_sensitive_word_logs_session_id'), table_name='sensitive_word_logs')
    op.drop_index(op.f('ix_sensitive_word_logs_content_hash'), table_name='sensitive_word_logs')
    op.drop_index('idx_sensitive_word_logs_user_action', table_name='sensitive_word_logs')
    op.drop_index('idx_sensitive_word_logs_created', table_name='sensitive_word_logs')
    op.drop_table('sensitive_word_logs')
    # ### end Alembic commands ###
